name: Production Deployment
on:
  push:
    branches:
      - ci-debug

env:
  ACNH_ENV: ${{ secrets.env_trial }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying trough pm2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.deployment_host }}
          username: ${{ secrets.deployment_user }}
          key: ${{ secrets.deployment_key }}
          port: ${{ secrets.deployment_port }}
          envs: ACNH_ENV
          script: |
            cd /opt/ACNH-telegram-bot-helper
            git pull
            echo -e "$ACNH_ENV" > .env
            pm2 status
            pm2 restart ACNH-bot-production --update-env --time
            sleep 3
            pm2 status
            pm2 logs ACNH-bot-production --err --nostream --timestamp
          